### ISSUE TITLE
Widget not working after reload

### ISSUE THREAD

**Issue by IHateMyKite** [IHateMyKite/UnforgivingDevices#150]
**Describe the bug**
Sometimes when loading the game, the iWidget will break, preventing widgets from working

**To Reproduce**
Save a game and load it. Possibly game restarted first

**Expected behavior**
Loading a game should not break widgets

**Screenshots**
Can't show hiden widgets

**Additional context**
From looking at the save, it looks like that source of issue is this
![pic](https://user-images.githubusercontent.com/103142567/235354928-7541641f-fa50-4df7-b800-5109ab81edd4.png)

Last stack before utility.wait

```
   PROPGET HUD_MENU self ::temp17
   PROPGET WidgetRoot self ::temp18
   STRCAT ::temp18 ::temp18 .outputReady
   CALLSTATIC UI GetBool ::temp19 2 ::temp17 ::temp18
   ASSIGN msgReady ::temp19
   NOT ::temp19 msgReady
   JMPF ::temp19 8
   PROPGET HUD_MENU self ::temp17
   PROPGET WidgetRoot self ::temp18
   STRCAT ::temp18 ::temp18 .outputReady
   CALLSTATIC UI GetBool ::temp20 2 ::temp17 ::temp18
   ASSIGN msgReady ::temp20
==>CALLSTATIC utility Wait ::NoneVar 1 0.1
   JMP -8
   PROPGET HUD_MENU self ::temp17
   PROPGET WidgetRoot self ::temp18
   STRCAT ::temp18 ::temp18 .outputMessage
   CALLSTATIC UI GetString ::temp17 2 ::temp17 ::temp18
   ASSIGN msg ::temp17
   PROPGET HUD_MENU self ::temp18
   PROPGET WidgetRoot self ::temp17
   STRCAT ::temp17 ::temp17 .outputMessage
   CALLSTATIC UI SetString ::NoneVar 3 ::temp18 ::temp17 
   PROPGET HUD_MENU self ::temp18
   PROPGET WidgetRoot self ::temp17
   STRCAT ::temp17 ::temp17 .outputReady
   CALLSTATIC UI SetBool ::NoneVar 3 ::temp18 ::temp17 false
   RETURN msg
```

@iiw2012  can you please give it a look ? If not, I will try to fix it, but as you are more experienced with the widget system, it would be more optimal for you.

Save in question is attached. Note that I removed before one mod, which is why resaver will say that there are unattached references. I managed to get this bug before even when I didn't install/uninstall any of the mods.
[Save10_583C64EB_0_4661757374_Tamriel_000005_20230430131559_1_1.zip](https://github.com/IHateMyKite/UnforgivingDevices/files/11361393/Save10_583C64EB_0_4661757374_Tamriel_000005_20230430131559_1_1.zip)

**Comment by iiw2012** [comment]
I'll take a look.

I've also encountered iWidget problems after loading saves. It happened to me if I switched between saves with native controls and controls on iWW within single game session. At some point, the iWW interface broke (moved to the side). And everything was restored only after restarting the whole game. I wonder if it is related to this issue.

I tried to dig out the core problem, but since such an issue arose only if you activly use saves with different rendering engines (which is hardly a frequent case in a normal game), I abandoned the research.

**Comment by IHateMyKite** [comment]
Looking at the code of iWidget, I'm like 100% percent that it is caused by that mod. More specially, it looks like that it doesn't take in account for the multiple threads in most of the functions. So if someone (like me) uses Papyrus NG, it can cause the load function to run multiple times at once. I will try to do some testing with Papyrus NG filter, to see if its caused by it. Alternatively, there will need to be made patch for iWidget that fixes it.

**Comment by iiw2012** [comment]
If it is iWW issue then you could report to the author on Nexus (https://www.nexusmods.com/skyrimspecialedition/mods/36457?tab=bugs). He is quite active there. I asked him about setPos/setSize issues and he helped me.

In the meantime, I'll try to find workarounds on how to use the mod in these conditions.

**Comment by IHateMyKite** [comment]
I have reported the issue, but after thinking about it, it looks like the issue is in the action scripts. I have manually changed the value in the blocked thread so it can finish, but it still doesn't work. So my idea is that something in the action script is preventing the HUD menu from correctly setting .outputReady

**Comment by iiw2012** [comment]
There are constructions like:
```
	UI.InvokeString(HUD_MENU, Widget Root + ".loadText", s)
	id = (_getMessageFromFlash()) As Int
```
And the boolean ".outputReady" is used to detect that query to the flash is ready. One boolean for every query.

So if we've got two very fast call to any functions in script and they ovelapped while sending queries and recieving results then the first call get its ".outputReady", null it, and the second query will never get its result.

**Comment by IHateMyKite** [comment]
That is what was I also thinking, but issue is that even when I edited the while loop variable msgReady to true, it still didn't fix the issue. But it's possible, and I get so unlucky that the issue just appeared again every time I reloaded the game after changing the save file.

**Comment by iiw2012** [comment]
I still don't understand why there is an overlap of iWW function calls.

Lets assume that the issue is in the _getMessageFromFlash function (in papyrus or in actionscript behind). This function is called only when controls are created: loadText, loadWidget, loadMeter. And all calls of these functions are collected in one place:
https://github.com/IHateMyKite/UnforgivingDevices/blob/88d663d373937c6034786c1e826de2dd48d6bee2/Scripts/Source/UD_WidgetControl.psc#L1112-L1138
There are plain cycles inside InitMeters, InitIcons and InitText with sequential calls of loadMeter, loadWidget and loadText. Any parallel calls are impossible here, or I don't understand how papyrus scripts work. Or there's some obvious mistake that I don't see.

**Comment by IHateMyKite** [comment]
I think I have found the issue and fixed it. Basically, the initiation was not in reality serialized. It was possible for the meters to be initiated 2 times at once. Specifically, the issue is that the function InitWidgetsRequest doesn't initiate the widgets, but instead call update function. Next piece of puzzle is that the InitMeters, InitText and InitIcons and is extremely slow and processing all these takes at least 3 seconds with papyrus NG. Because of that, it was possible for user to try to use widgets while they were still initiating. So my guess is that if you for example try to change color/value of meter while its not loaded, it will break the iWW.

**Comment by IHateMyKite** [comment]
Didn't get this issue in long time. Closing.
