### ISSUE TITLE
NPC Registration is messing with DD Hobble Skirt Effect

### ISSUE THREAD

**Issue by iiw2012** [IHateMyKite/UnforgivingDevices#153]
**Describe the bug**
Magic effect from DD zadx_effHobbleSkirt (FormID: XX022226) is removed after NPC registration in NPCSlot.

**To Reproduce**
Best way to see:
1. Get unregistered NPC (Follower).
2. Equip on NPC any boot with high heels.
3. Equip on NPC Petsuit (it has zadx_effHobbleSkirt that compensates HH shift).
4. Register NPC in UD.
5. zadx_effHobbleSkirt effect will reappear and then dissapear for good. HH shift will not be compensated and NPC will float above the ground.
6. To check the absence of effect you could also execute console command HasMagicEffect XX022226 (XX - load order of Devious Devices - Expansion.esm).

**Expected behavior**
Hobble Skirt Effect must persist.

**Screenshots**
![image](https://user-images.githubusercontent.com/110040088/235434416-3acd5a3a-1284-4135-b4d9-a204d6c7d528.png)

**Comment by IHateMyKite** [comment]
This bug have actualy nothing to do with UD, or even DD. Its engine issue. Basically, all it takes to remove the effect is to just move "any" item from npc inventory. This forces some kind of refresh which removes to enchant. I had my own adventure when finding out, when I was reworking gags for DD. I was puzzled why the gag effect was not staying on the NPC, and then found out that its just garbage engine. Even when I have all engine fixes in existence, none of them fixes this. But when testing It, I found one more interesting thing. And that is that if you put the enchant on inventory device, it will not be removed... My theory was that issue is because the armor holding the enchant have no name (because no render device have name). I have solved the issue with gags by just throwing the enchant out of window, and instead added alias slots and quest which adds update the gags only for closest actors. So technically, it might be also fixable by adding ability that will be applied in place of enchantment. Issue with this, then not even abilities work reliably, as when npc changes cell, it will also remove the ability... Best would be to find a way to not use anything magic effect related on npcs. That is why I did the whole rework of orgasm system, as before it was using abilities on npcs. Now it uses orgasm updater script.

**Comment by IHateMyKite** [comment]
Also, why is it needed for npcs to have hobble skirt effect? Even when they have the skirt, they still move at normal speed (at least in my game)

**Comment by IHateMyKite** [comment]
Well, DD is not build to handle NPCs, so this is only the tip of the iceberg. And until Bethesda gets its shit together, this issue will never be fixed. Was thinking for some time about getting into the dll business, but I have no time to learn how to reverse engineer the game to learn what part is the source of the issue.  Might be a good idea to report it to some people who know their way with engine fixes, and see if they would be interested in fixing it.

**Comment by IHateMyKite** [comment]
Closing this for now, as there is realistically way for UD to fix this issue.
