### ISSUE TITLE
Zadlibs_UDPatch::VIbrateEffect not setting zadVibrateFaction

### ISSUE THREAD

**Issue by SkyLover37** [IHateMyKite/UnforgivingDevices#154]
zadVibrateFaction does not get added/set during default vibrate function, this seems like something that should be considered to be added to the default vibrate function as some mods rely on this being set to detect vibration.

**Comment by IHateMyKite** [comment]
The VibrateEffect function should work exactly same as DD function if actor have no UD vibrator. Issue is that I have bad feeling about compatibility, if UD will tinker with the faction. There is also question how should the faction be set, as actor can have any number of vibrators, so there is basically not a maximum value. Only way I can think of is to just use the maximum value of the currently turned on vibrator. But the issue is then how to know if the faction should be set back to 0 ? As, the DD use the faction to know if vibration effect is on. For that reason, it will be impossible for UD to know if default DD vibration effect is on, or if UD just changed the value. I will try to think about the solution, but it will not be easy.
