### ISSUE TITLE
(Minor) Added MAO modifier sometimes fail to trigger

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#18]
Description: 100% Manifest on Orgasm modifier, added through menu sometimes fail to equip any items. Cause is unknown (parsing?), can't tell if the same issue happens for randomly generated modifier. Happened more than 5 times for me.
Device: Grand vaginal plug
Orgasm type: forced with plug (tested on self forcing with breathplay minigame, also happens there)
Other devices: only anal plug.
Written modifier syntax:
![изображение](https://user-images.githubusercontent.com/30041703/163900682-406ef0c5-4e75-454b-9588-a03eb3738fe4.png)

It is not necessary always happen, sometimes it is capable to equip item, sometimes not.

Version of skyrim: SE
Version of mod: 2.0b9 commit https://github.com/IHateMyKite/UnforgivingDevices/commit/84d5fb1d26527d575db04faa64fc5b2df887538c
Used patches: DD+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
MAO is implemented [here](https://github.com/IHateMyKite/UnforgivingDevices/blob/84d5fb1d26527d575db04faa64fc5b2df887538c/Scripts/Source/UD_CustomDevice_RenderScript.psc#L4614-L4647). I think that the problem is that on [this ](https://github.com/IHateMyKite/UnforgivingDevices/blob/84d5fb1d26527d575db04faa64fc5b2df887538c/Scripts/Source/UD_CustomDevice_RenderScript.psc#L4618)line should be randomInt(0,99), but that would not make it so frequent. You can try adding some logging here to see what the values are and if the loc_chance variable is truely the 100. Also, did you change the MCM setting for MAO modifier??

**Comment by BreadDain** [comment]
Yes I had modified orgasm chance settings, which also affect manually added modifiers values. If I have a multiplier of 60 in config and type in MAO100,1 the final chance would be 60%. I don't believe that's an expected behaviour.

Applying the modifier to typed/showed in tooltip values might sound reasonable, but that would cause them change retroactively when mulltiplier is changed as well.

**Comment by IHateMyKite** [comment]
It is expected behavior. The chance can be any number from 1-100. It can be randomly generated with patcher or created manually. The MCM settings works as way to modify this value **relatively** on runtime. If chance is 10% and modifier is 50%, final MAO will be 5%.

**Comment by BreadDain** [comment]
Closing this then.
