### ISSUE TITLE
Helper stuck in minigame animation for devices without registered animations

### ISSUE THREAD

**Issue by AndrejAndb** [IHateMyKite/UnforgivingDevices#181]
**Describe the bug**
In case when device not have minigame animation. minigame with helper - cause stuck helper in minigame state

**To Reproduce**
1. Start minigame with helper for device `zad_DeviousPetSuite`
2. interrupt minigame
3. Helper stuck in animation (`.spectator` animation)

**Expected behavior**
Helper must also released from animation

**Comment by AndrejAndb** [comment]
https://github.com/IHateMyKite/UnforgivingDevices/blob/3e39cf3c45e8f694cde73f610da4ab91a3d6dcf9/Scripts/Source/UD_CustomDevice_RenderScript.psc#L6497

looks need something like
```
If hasStruggleAnimation[0] > 0 || hasStruggleAnimation[1] > 0
```

**Comment by iiw2012** [comment]
_PickAndPlayStruggleAnimation function works as follows. If there is no suitable paired animation, an attempt is made to find separate solo animations for the player and follower. If there is not even a solo animation for the player (which is very strange, and should signal that the registration files are not loaded), then the output of the _PickAndPlayStruggleAnimation function will be 0 for the first element. But the follower can get some animation in the same function from the “.spectator” section and the second element of the returned array will have some positive number.

So yes, in this exotic case, the follower will hang in the animation state, because the minigame will not be followed by StopAnimation since the player didn't have any animation. That is an error on my side.

The proposed fix will solve the issue. Although the issue, as I wrote above, is more about how one can even get into such a situation.

**Comment by iiw2012** [comment]
Okay, I get it. I'm so used to my animations that I forgot that petsuit won't work without them.

So yes, if my animation package is not installed, trying to struggle out of the petsuit will result in the above situation.

As far as I understand, the animations for petuit should already be in DD NG. So I can fix the json files to use the existing animations without having to install my extension.

Alternatively, all (or part) of my animations can be added to the main mod so as not to confuse people :) If I add animations in the future, I will do it with a separate json file to avoid conflicts.

**Comment by IHateMyKite** [comment]
Glad to see you back.

> Okay, I get it. I'm so used to my animations that I forgot that petsuit won't work without them.
> 
> So yes, if my animation package is not installed, trying to struggle out of the petsuit will result in the above situation.
> 
> As far as I understand, the animations for petuit should already be in DD NG. So I can fix the json files to use the existing animations without having to install my extension.
> 
> Alternatively, all (or part) of my animations can be added to the main mod so as not to confuse people :) If I add animations in the future, I will do it with a separate json file to avoid conflicts.

Same, I never toughed the animation pack after installing it so didnt occur to me that this issue can happen because of missing animation
