### ISSUE TITLE
(Minor) Hardcore mod unexpected lock of controls

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#36]
Description: playing with Hardcore mod on sometimes lock controls on very unexpected situations. Usually it is related to struggling out/finishing a minigame with devices that are not relate to being 'Helpless', such as piercings or plugs. Controls lock up until next minigame finishes (verify), then it goes back to normal.

Expected result: loss of control only during restrictive devices, arm restraints, blindfolds, hoods and etc.
Actual result: in addition to ER some random devices also lock all controls randomly when being unequipped.

Version of skyrim: SE
Version of mod: 2.0b10
Used patches: DD5.1+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
Can't directly replicate, but I think I got this bug once when play testing. But it went after the next minigame, and so I didn't give it that much attention (game reloading will also enable player, so you can always save and load). I gave it a look and I think that the problem is [here](https://github.com/IHateMyKite/UnforgivingDevices/blob/c9ea0c50786de6d67d4b45fa2a839c5b5c1e3ea1/Scripts/Source/UDCustomDeviceMain.psc#L339-L343). I don't remember why I added abMovement = False, but it doesn't really do anything.

**Comment by IHateMyKite** [comment]
Reworked the code to use disable in parallel process script. This should hopefully reduce chance of player getting lost of control when minigame ends.
