### ISSUE TITLE
(Compatibility) Perks usage

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#64]
Description: making code rely on vanilla perks will inadvertently lead to compatibility issues with mods that modify perk behaviour such as [Ordinator](https://www.nexusmods.com/skyrimspecialedition/mods/1137). In case of the latter - NPC calculation will work fine but player perks will not be always accounted since most of them are replaced while others are removed entirely from player (record replaced with NPC-only version of perk)

Version of skyrim: SE
Version of mod: 2.0b13

**Comment by IHateMyKite** [comment]
All used perks are stored in form list UD_AgilityPerks_FLST, UD_StrengthPerks_FLST and UD_MagickPerks_FLST. Compatibility can be fixed by creating some new quest which will check on game reload if the incompatible mod is installed. In that case, the perks can be fetched with GetMeMyForm and added to formlist on runtime. No new patch will be required.

**Comment by IHateMyKite** [comment]
Implemented with 35db9ec. Closing.
