### ISSUE TITLE
(Compatibility) Installed Devious Strike makes UD spam messages

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#65]
Description: When Devious Strike despawns one of the mods enemies (Strikers) and strips them from bondage, UD produces a lot of errors both in message popup area and console

![изображение](https://user-images.githubusercontent.com/30041703/176956847-be996592-8c28-4581-99bb-57055e3c6df3.png)
![изображение](https://user-images.githubusercontent.com/30041703/176956871-561eb4e2-69fc-403b-9ac9-42de4f6c7bcd.png)

Version of skyrim: SE
Version of mod: 2.0b13

**Comment by IHateMyKite** [comment]
These errors might seems bad, but they are really not. What is it saying is that Devious Strike tried to lock device which occupy slot which is already occupied by other device. This is little complicated to explain and even DD didn't have this safety check.
In general every render device takes some slot. And all slots have associated some devious keyword. But every device have only one "major" keyword, which is used to check if device is not in conflict. 

But lets have following example: Player will get locked in pair of plugs. It will be device which takes both Anal and Vaginal slot, but doesn't have vaginal keyword. But the major keyword will be only zad_deviouspluganal. Now lets say that another device will try to be locked on. Simple vaginal plug, which have major keyword zad_deviousplugvaginal. DD will actually allow the device to be locked on, because they have different major keywords. And the skyrim engine works in a way that if there is attempt to equip armor in to slot which is already occupied, it will swap the armor. But in this case that is not possible because devices are equipped with function actor.equipitem() with argument to prevent armor unequip. This makes DD to add render device on to actor but not equip it. This is very bad for UD, because all information is stored in Render device. So I had to add check to see if device can be even equipped.

But, now back to the issue. It's strange that it is calling LockDevice when they are despawned. Did you just kill them or did they despawned because they defeated you? It's also possible that issue is unrelated to them despawning, maybe some just spawned outside your view.

**Comment by BreadDain** [comment]
It might got caused by an actor spawning outside of sight, yes. And I've already seen some ERRORs related to strikers in previous version of UD, it just didn't appear to be spamming the notification area.

**Comment by BreadDain** [comment]
Errors related to strikers are keep popping up all the time but it seems like UD is capable of resolving them without piling active scripts in the save file. I can't reproduce notification area message spam in any way, it happened only once.
